server:
  port: 8207

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  application:
    name: service-orders
  profiles:
    active: dev
  # MySQL连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: pwb2001
  redis:
    host: 172.20.10.9
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # rabbitMq
  rabbitmq:
    username: admin
    password: 123456
    host: localhost
    port: 5672
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yy/order/mapper/xml/*.xml
