server:
  port: 8160

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  application:
    name: service-user
  profiles:
    active: dev
  # MySQL连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_user?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: pwb2001
  redis:
    host: 172.20.10.9
    port: 6379
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yy/user/mapper/xml/*.xml

