server:
  port: 8208
spring:
  application:
    name: service-task
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456